services:
  - type: web
    name: jay-trading-hub-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

      - key: PYTHON_VERSION
        value: "3.11.9"

      - key: BOT_TOKEN
        sync: false

      - key: PAYSTACK_SECRET_KEY
        sync: false

      - key: MONGO_URI
        sync: false

      - key: RENDER_EXTERNAL_URL
        sync: false

      - key: MINI_APP_URL
        sync: false

      - key: GOLD_CHANNEL_ID
        sync: false

      - key: FOREX_CHANNEL_ID
        sync: false

      - key: ADMIN_TELEGRAM_ID
        sync: false

      - key: ADMIN_API_KEY
        sync: false

      - key: TELEGRAM_WEBHOOK_SECRET
        sync: false

      - key: PAYSTACK_ACCOUNT_COUNTRY
        value: "ghana"

      - key: PAYMENT_CURRENCIES
        value: "GHS"

      - key: BOT_USERNAME
        value: "JayEmpire_bot"

      - key: MIN_WITHDRAWAL_GHS
        value: "50"

      - key: WITHDRAWAL_COOLDOWN_DAYS
        value: "7"
