services:
  - type: web
    name: telegram-paystack-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: BOT_TOKEN
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: MINI_APP_URL
        sync: false
      - key: GOLD_CHANNEL_ID
        sync: false
      - key: FOREX_CHANNEL_ID
        sync: false
